<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Images\Fasticon-Comic-Iphone-Graph.ico</ApplicationIcon>
    <PlatformTarget>x64</PlatformTarget>
    <StartupObject></StartupObject>
	<Nullable>disable</Nullable>
	<IncrementVersionOnBuild>1.yyyy.Mdd.Hmm</IncrementVersionOnBuild>
	<AssemblyVersion>1.1.1.0</AssemblyVersion>
	<FileVersion>1.1.1.0</FileVersion>
	<Version>1.1.1.0</Version>
	  <EnableInterceptors>true</EnableInterceptors>
	  <InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.Extensions.Configuration.Binder.SourceGeneration</InterceptorsNamespaces>
   </PropertyGroup>

  <ItemGroup>
    <None Remove="Fasticon-Comic-Iphone-Graph.ico" />
    <None Remove="Images\background.png" />
    <None Remove="Images\S7ExpertLogo.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\Fasticon-Comic-Iphone-Graph.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JsonFlatFileDataStore" Version="2.4.2" />
    <PackageReference Include="LinkDotNet.BuildInformation" Version="2.1.5" />
    <PackageReference Include="MahApps.Metro.IconPacks" Version="6.2.1" />
    <PackageReference Include="Material.Icons.WPF" Version="3.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
	 
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
	 
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
	 
    <PackageReference Include="ModernWpfUI" Version="0.9.6" />
	 
    <PackageReference Include="OxyPlot.Wpf" Version="2.2.0" />
	 
    <PackageReference Include="TaskScheduler" Version="2.12.2" />
	 
    <PackageReference Include="WindowsAPICodePack" Version="8.0.15.2" />
	 
    <PackageReference Include="Workstation.UaClient" Version="3.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\background.png" />
    <Resource Include="Images\background1.jpeg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Fasticon-Comic-Iphone-Graph.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\S7ExpertLogo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Warnings.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Alarms.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
    <Folder Include="Themes\" />
  </ItemGroup>

</Project>
